name: release

on:
  push:

  workflow_dispatch:


jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install CMSIS-Toolbox
        run: |
          . <(curl https://aka.ms/vcpkg-init.sh -L)
          . ~/.vcpkg/vcpkg-init
          vcpkg x-update-registry arm

      - name: Compile
        run: |
          . ~/.vcpkg/vcpkg-init
          vcpkg use uv2csolution
          cd MDK-ARM
          uv2csolution CoreMark.uvprojx
          vcpkg activate
          cpackget init https://arduino.luatos.com/cmsis-pack/AirM2M.pidx
          cpackget add AirM2M.AIR001_DFP.1.1.3
          cpackget init https://www.keil.com/pack/index.pidx
          armlm activate -product KEMDK-COM0 -server https://mdk-preview.keil.arm.com
          cbuild CoreMark.csolution.yml --update-rte --packs
      
      - name: release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: "Latest"
          artifacts: "MDK-ARM/out/CoreMark/Project/CoreMark.hex, MDK-ARM/out/CoreMark/Project/CoreMark.bin"